In [1]:
import numpy as np

In [2]:
data = np.random.randn?

In [3]:
data = np.random.randn(3,50)

In [8]:
np.alltrue(data > 0, axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False])

In [12]:
np.count_nonzero(data, 0)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3])

In [10]:
data[0]

array([ 0.06918108, -1.64174207, -0.3753262 , -0.20022818, -0.56983012,
        0.4092829 ,  1.13923872,  1.00669558,  0.79773119, -0.38283425,
       -0.17219441, -0.06135774, -0.97580586,  0.39128276, -1.76576682,
       -0.81089776, -0.92573403,  0.94154128, -1.85911348,  0.28142125,
       -0.33485176,  1.4613996 ,  0.23777239, -1.83087957, -0.80301427,
        0.83007153,  0.74293623,  0.07338203, -0.31092265, -0.55891138,
       -0.54791732,  2.18357896,  0.44802169,  0.36781076, -0.6838105 ,
       -1.73880086, -0.05396723,  1.35593384, -0.08085876,  0.67437283,
        1.77657802, -0.54861899, -0.6123747 ,  0.87557376, -1.27180235,
       -0.64944952,  1.5315908 ,  2.62015865,  2.03850718,  0.58239833])

In [25]:
from zipline.pipeline.fundamentals.reader import Fundamentals
from zipline.pipeline.builtin import TradingDays,QTradableStocks
from zipline.research import run_pipeline, select_output_by
from zipline.pipeline import Pipeline
from zipline.pipeline.data import USEquityPricing
from zipline.pipeline.factors import SimpleMovingAverage

In [33]:
def make_pipeline():
    base_universe = QTradableStocks()
    # 10-day close price average.
    mean_10 = SimpleMovingAverage(
        inputs=[USEquityPricing.close], window_length=10, mask=base_universe)

    return Pipeline(
        columns={
            'mean_10': mean_10,
        }, 
        #screen=base_universe
    )

In [34]:
result = run_pipeline(make_pipeline(), '2018-4-20', '2018-4-26')

In [35]:
select_output_by(result,stock_codes=['600645','600771','300001','600076'])

mean_10
2018-04-20 00:00:00+00:00 特锐德(300001)    13.098
                          康欣新材(600076)      NaN
                          中源协和(600645)      NaN
                          广誉远(600771)    49.842
2018-04-23 00:00:00+00:00 特锐德(300001)    13.093
                          康欣新材(600076)      NaN
                          中源协和(600645)      NaN
                          广誉远(600771)    49.759
2018-04-24 00:00:00+00:00 特锐德(300001)    13.078
                          康欣新材(600076)      NaN
                          中源协和(600645)      NaN
                          广誉远(600771)    49.561
2018-04-25 00:00:00+00:00 特锐德(300001)    13.076
                          康欣新材(600076)      NaN
                          中源协和(600645)      NaN
                          广誉远(600771)    49.684