In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from scipy import stats

In [4]:
fs_df = pd.DataFrame(np.arange(1,26).reshape(5,5).T)

In [5]:
epsilon_sect = pd.Series([1,2,3,4,5])

In [9]:
x = fs_df[0].values

In [17]:
x

array([1, 2, 3, 4, 5])

In [18]:
from scipy import linalg

In [19]:
arr = np.array([[1, 2],
                [3, 4]])

In [20]:
iarr = linalg.inv(arr)

In [21]:
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
X = np.arange(1,19).reshape(6,3) + np.random.random(18).reshape(6,3)
Y = np.arange(1,19).reshape(6,3) + np.random.random(18).reshape(6, 3)

In [57]:
beta = linalg.inv(X.T.dot(X)).dot(X.T).dot(Y)

In [61]:
X[-1] * beta[-1]

array([-8.12185263, 11.77245851, 23.20344273])

In [62]:
Y[-1]

array([16.88510944, 17.38971088, 18.14481606])

In [65]:
SECTOR_INDEX_MAPS = {
    101: '399614',
    102: '399617',
    103: '399619',
    104: '399241',
    205: '399616',
    206: '399618',
    207: '399622',
    308: '399621',
    309: '399613',
    310: '399615',
    311: '399620'
}

In [12]:
PPM = 21

In [23]:
X = np.array([1]* PPM *12).reshape(6 * PPM,2)

In [18]:
np.cumprod(X[1:11*PPM+1, :] / X[:11*PPM], axis=1)[-1]

array([1.])

In [24]:
np.log10(X)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.

In [25]:
class A():
    """A"""
    pass

In [26]:
A.__doc__

'A'